/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VpnRouteImport } from './routes/vpn'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AiPricingRouteImport } from './routes/ai-pricing'
import { Route as AiBotRouteImport } from './routes/ai-bot'
import { Route as IndexRouteImport } from './routes/index'

const VpnRoute = VpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPricingRoute = AiPricingRouteImport.update({
  id: '/ai-pricing',
  path: '/ai-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBotRoute = AiBotRouteImport.update({
  id: '/ai-bot',
  path: '/ai-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-bot': typeof AiBotRoute
  '/ai-pricing': typeof AiPricingRoute
  '/help': typeof HelpRoute
  '/vpn': typeof VpnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-bot': typeof AiBotRoute
  '/ai-pricing': typeof AiPricingRoute
  '/help': typeof HelpRoute
  '/vpn': typeof VpnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-bot': typeof AiBotRoute
  '/ai-pricing': typeof AiPricingRoute
  '/help': typeof HelpRoute
  '/vpn': typeof VpnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-bot' | '/ai-pricing' | '/help' | '/vpn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-bot' | '/ai-pricing' | '/help' | '/vpn'
  id: '__root__' | '/' | '/ai-bot' | '/ai-pricing' | '/help' | '/vpn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBotRoute: typeof AiBotRoute
  AiPricingRoute: typeof AiPricingRoute
  HelpRoute: typeof HelpRoute
  VpnRoute: typeof VpnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vpn': {
      id: '/vpn'
      path: '/vpn'
      fullPath: '/vpn'
      preLoaderRoute: typeof VpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-pricing': {
      id: '/ai-pricing'
      path: '/ai-pricing'
      fullPath: '/ai-pricing'
      preLoaderRoute: typeof AiPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-bot': {
      id: '/ai-bot'
      path: '/ai-bot'
      fullPath: '/ai-bot'
      preLoaderRoute: typeof AiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBotRoute: AiBotRoute,
  AiPricingRoute: AiPricingRoute,
  HelpRoute: HelpRoute,
  VpnRoute: VpnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
